;;;; pbkdf2.import.scm - GENERATED BY CHICKEN 4.13.0 -*- Scheme -*-

(eval '(import chicken scheme srfi-1 srfi-4 srfi-13 hmac sha1 sha2))
(##sys#register-compiled-module
  'pbkdf2
  (list)
  '((pbkdf2-hmac-sha1 . pbkdf2#pbkdf2-hmac-sha1)
    (pbkdf2-hmac-sha256 . pbkdf2#pbkdf2-hmac-sha256)
    (pbkdf2-hmac-sha384 . pbkdf2#pbkdf2-hmac-sha384)
    (pbkdf2-hmac-sha512 . pbkdf2#pbkdf2-hmac-sha512))
  (list)
  (list))

;; END OF FILE
